import argparse
import torch

parser = argparse.ArgumentParser(description='MACIL_SD')
parser.add_argument('--modality', default='MIX2', help='the type of the input, AUDIO,RGB,FLOW, MIX1, MIX2, or MIX3, MIX_ALL')
parser.add_argument('--rgb-list', default='list/rgb.list', help='list of rgb features ')
parser.add_argument('--flow-list', default='list/flow.list', help='list of flow features')
parser.add_argument('--audio-list', default='list/audio.list', help='list of audio features')
parser.add_argument('--test-rgb-list', default='list/rgb_test.list', help='list of test rgb features ')
parser.add_argument('--test-flow-list', default='list/flow_test.list', help='list of test flow features')
parser.add_argument('--test-audio-list', default='list/audio_test.list', help='list of test audio features')
parser.add_argument('--model_dir', default='ckpt/macil_sd.pkl', help='ckpt dir')
parser.add_argument('--gt', default='list/gt.npy', help='file of ground truth ')
#parser.add_argument('--gpus', default='0', type=str,  help='gpus')
parser.add_argument('--lr', type=float, default=0.0002, help='learning rate (default: 0.0001)')
parser.add_argument('--batch-size', type=int, default=128, help='number of instances in a batch of data (default: 128)')
parser.add_argument('--workers', type=int, default=8, help='number of workers in dataloader')
parser.add_argument('--model-name', default='macil_sd', help='name to save model')
parser.add_argument('--pretrained-ckpt', default=None, help='ckpt for pretrained model')
parser.add_argument('--num_classes', type=int, default=1, help='number of class')
parser.add_argument('--a_feature_size', type=int, default=128)
parser.add_argument('--v_feature_size', type=int, default=1024)
parser.add_argument('--m', type=float, default=0.91, help='update teacher model')
parser.add_argument('--dataset-name', default='XD-Violence', help='dataset to train on (default: )')
parser.add_argument('--max_seqlen', type=int, default=200, help='maximum sequence length during training (default: 750)')
parser.add_argument('--max-epoch', type=int, default=100, help='maximum iteration to train (default: 100)')
parser.add_argument('--warmup-epochs', type=int, default=35, help='number of epochs for lambda warm-up schedule')
parser.add_argument('--lamda_a2b', type=float, default=1.4)
parser.add_argument('--lamda_a2n', type=float, default=0.5)
parser.add_argument('--lamda_v', type=float, default=0.1, help='Weight for uni-modal visual contrastive loss')
parser.add_argument('--lamda_a', type=float, default=0.1, help='Weight for uni-modal audio contrastive loss')
parser.add_argument('--lamda_cof', type=float, default=0.05)
parser.add_argument('--hid_dim', type=int, default=128)
parser.add_argument('--ffn_dim', type=int, default=128)
parser.add_argument('--num_stages', type=int, default=3)
parser.add_argument('--nhead', type=int, default=4)
parser.add_argument('--dropout', type=float, default=0.1)
parser.add_argument('--dropoutGCN', type=float, default=0.6)
parser.add_argument('--dropout0', type=float, default=0.1)
parser.add_argument('--model', default='HyboNet', help='which encoder to use, can be any of [Shallow, MLP, HNN, GCN, GAT, HGCN, HyboNet]')
parser.add_argument('--manifold', default='Lorentz', help='which manifold to use, can be any of [Euclidean, Hyperboloid, PoincareBall, Lorentz]')
parser.add_argument('--c', default=None, help='hyperbolic radius, set to None for trainable curvature')
parser.add_argument('--num-layers', type=int, default=2, help='layers of hgcn')
parser.add_argument('--act', default='leaky_relu', help='which activation function to use (or None for no activation)')
parser.add_argument('--dim', type=int, default=32, help='embedding dimension')
parser.add_argument('--bias', type=int, default=1, help='whether to use bias (1) or not (0)')
parser.add_argument('--use-att', type=int, default=0, help='whether to use hyperbolic attention or not')
parser.add_argument('--local-agg', type=int, default=0, help='whether to local tangent space aggregation or not')
parser.add_argument('--tie_weight', default=True, help='whether to tie transformation matrices')
parser.add_argument('--feat-dim', type=int, default=256, help='input size of feature for HGCN (default: 2048)')
#parser.add_argument('--cuda', type=int, default=0, help='which cuda device to use (-1 for cpu training)')
#parser.add_argument('--device', type=str, default='cuda' if torch.cuda.is_available() else 'cpu')
parser.add_argument('--device', type=str, default='cuda:0' if torch.cuda.is_available() else 'cpu',help="Device to use for training, e.g., 'cpu', 'cuda', 'cuda:0', 'cuda:1'")
parser.add_argument('--log_path', type=str, default='training.log', help='Path to save the log file.')
parser.add_argument('--checkpoint_path', type=str, default='./ckpt', help='Path to save the model checkpoints.')
parser.add_argument('--seed', type=int, default=2026, help='random seed for reproducibility')
#伪标签相关参数
parser.add_argument('--pseudo-warmup-epochs', type=int, default=15, help='number of epochs before starting pseudo-labeling')
parser.add_argument('--lamda_pseudo', type=float, default=0.05, help='weight for the pseudo-labeling loss')
parser.add_argument('--pseudo-alpha', type=float, default=0.8, help='alpha for gaussian kernel mining')
parser.add_argument('--pseudo-b_left', type=float, default=2.0, help='left decay factor for asymmetric kernel')
parser.add_argument('--pseudo-b_right', type=float, default=5.0, help='right decay factor for asymmetric kernel')
parser.add_argument('--pseudo_ramp_up_epochs', type=int, default=15, help='number of epochs for pseudo lambda to ramp up to its final value')
parser.add_argument('--train-data-ratio', type=float, default=1.0,help='Ratio of training data to use (e.g., 0.1 for 10%)')
parser.add_argument('--test-data-ratio', type=float, default=1.0,help='Ratio of test data to use (e.g., 0.1 for 10%)')